spring.application.name=api
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8083/eureka
eureka.instance.prefer-ip-address=true


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=RAG API
info.app.description=Servicio de consultas RAG
info.app.version=1.0
############################################
# DATASOURCE (PostgreSQL)
############################################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

ollama.url=http://localhost:11434
ollama.model=qwen3:8b
ollama.embedding.model=nomic-embed-text
spring.datasource.hikari.connection-init-sql=SET client_encoding TO 'UTF8'

spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=10